### ISSUE TITLE
panic: async: EOF

### ISSUE THREAD

**Issue by jabteles** [blinklabs-io/bluefin#210]
```
panic: async: EOF

goroutine 3935 [running]:
github.com/blinklabs-io/bluefin/internal/tx.submitTxNtN.func1()
        /code/internal/tx/tx.go:442 +0x8e
created by github.com/blinklabs-io/bluefin/internal/tx.submitTxNtN in goroutine 3812
        /code/internal/tx/tx.go:439 +0x1a5
```

**Comment by agaffney** [comment]
This is the same problem as #204
